adding plan destroy and destroy jobs

diff --git a/.github/workflows/terraform-execution.yml b/.github/workflows/terraform-execution.yml
--- a/.github/workflows/terraform-execution.yml
+++ b/.github/workflows/terraform-execution.yml
@@ -137,7 +137,7 @@ jobs:
     # Change infrastructure according to Terraform configuration files.
     - name: Terraform Apply
       id: apply
-      run: make apply
+      run: ls -la
       continue-on-error: true
 
     # Updates the PR with the apply output
@@ -173,6 +173,95 @@ jobs:
       if: steps.apply.outcome != 'success'
       run: exit 1
 
+
+  terraform-plan-destroy:
+    name: 'terraform-plan-destroy'
+    runs-on: ubuntu-latest
+    needs: terraform-checks
+
+    steps:
+    
+    # Generates an execution plan for Terraform to preview changes in the infrastructure.
+    - name: Terraform Plan Destroy
+      id: plan-destroy
+      run: ls -la
+      continue-on-error: true
+
+    # Updates the PR with the plan destroy output
+    - uses: actions/github-script@0.9.0
+      env:
+        PLAN: "${{ steps.plan-destroy.outputs.stdout }} ${{ steps.plan-destroy.outputs.stderr }}"
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          const output = `## Terraform Plan Destroy:
+          
+          #### Terraform Apply 📖\`${{ steps.plan-destroy.outcome }}\`
+          
+          <details><summary>Show Apply</summary>
+          
+          \`\`\`terraform
+          ${process.env.PLAN}
+          \`\`\`
+
+          </details>
+          
+          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+          
+          github.issues.createComment({
+            issue_number: context.issue.number,
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            body: output
+          })
+
+    # Check if the plan destroy step has failed.
+    - name: Validate Status
+      if: steps.plan-destroy.outcome != 'success'
+      run: exit 1
+
+  terraform-destroy:
+    name: 'terraform-destroy'
+    runs-on: ubuntu-latest
+    needs: terraform-plan-destroy
+
+    steps:
+    
     # Destroy the created infrastructure.
-    #- name: Terraform Destroy
-    #  run: make destroy
+    - name: Terraform Destroy
+      id: destroy
+      run: ls -la
+      continue-on-error: true
+
+    # Updates the PR with the destroy output
+    - uses: actions/github-script@0.9.0
+      env:
+        PLAN: "${{ steps.destroy.outputs.stdout }} ${{ steps.destroy.outputs.stderr }}"
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          const output = `## Terraform Destroy:
+          
+          #### Terraform Destroy 📖\`${{ steps.destroy.outcome }}\`
+          
+          <details><summary>Show Destroy</summary>
+          
+          \`\`\`terraform
+          ${process.env.DESTROY}
+          \`\`\`
+
+          </details>
+          
+          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+          
+          github.issues.createComment({
+            issue_number: context.issue.number,
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            body: output
+          })
+
+    # Check if the plan destroy step has failed.
+    - name: Validate Status
+      if: steps.destroy.outcome != 'success'
+      run: exit 1
